version: "3"
services:
  mysqlDB:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "my-app-db"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql
  uploader:
    image: mohammadathar/django-file-uploader
    volumes:
      - .:/appdir
    ports:
      - "8000:8000"
    depends_on:
      - mysqlDB
volumes:
  db:



